title = "local config"

[http]
host = "0.0.0.0"
port = "8000"

[log]
logFilePath = "./log/logrus.log"

[mysql]
host = "localhost"
port = "3306"
username = "root"
password = "root"

[redis]
host = "127.0.0.1:6389"
password = "yTo11xh0"
poolSize = 50
minIdleConns = 20
db = 0

[memcache]
host = "127.0.0.1:11211"
maxIdleConns = 2
timeout = 100
